export const ADMIN_ROUTE = '/admin'
export const SHOP_ROUTE = '/shop'
export const BASKET_ROUTE = '/basket'
export const ITEM_ROUTE = '/item'
export const ACCOUNT_ROUTE = '/account'
export const FAQ_ROUTE = '/faq'